spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
        - id : front
          predicates:
          - Host=front.leedohyun.com
          uri: http://home.front:3000
        - id : tool
          predicates:
          - Host=tool.leedohyun.com
          uri: http://tool:8080