server:
   forward-headers-strategy: framework
spring:
   application:
      name: gateway
   cloud:
      gateway:
         routes:
         -  id: tool
            predicates:
            - Host=tool.leedohyun.com
            uri: http://tool-service.tool.svc.cluster.local:80
         -  id: root-redirect
            predicates:
            - Host=leedohyun.com,www.leedohyun.com
            filters:
            - RedirectTo=302, https://home.leedohyun.com
            uri: no://op
         -  id: wordpress
            predicates:
            - Host=blog.leedohyun.com,wordpress.leedohyun.com
            uri: http://wordpress-service:80
         -  id: minio-api
            predicates:
            - Host=static.leedohyun.com
            uri: http://minio.minio.svc.cluster.local:9000
         -  id: minio-console
            predicates:
            - Host=minio.leedohyun.com
            uri: http://minio-console.minio.svc.cluster.local:9001
         -  id: redmine
            predicates:
            - Host=alm.leedohyun.com,redmine.leedohyun.com
            uri: http://redmine-service.redmine.svc.cluster.local:3000
         -  id: keycloak
            predicates:
            - Host=keycloak.leedohyun.com
            uri: http://keycloak-service.keycloak.svc.cluster.local:80
         -  id: architecture
            predicates:
            - Host=architecture.leedohyun.com
            uri: http://architecture-web-service.default.svc.cluster.local:80
         -  id: auth-api
            predicates:
            - Host=customer.leedohyun.com
            - Path=/api/auth/**
            uri: http://auth-api.customer.svc.cluster.local:8080
         -  id: order-api-customer
            predicates:
            - Host=customer.leedohyun.com
            - Path=/api/orders/**
            uri: http://order-api.customer.svc.cluster.local:8080
         -  id: customer-front
            predicates:
            - Host=customer.leedohyun.com
            uri: http://customer-front.customer.svc.cluster.local:3000
         -  id: auth-api-home
            predicates:
            - Host=home.leedohyun.com
            - Path=/api/auth/**
            uri: http://auth-api.customer.svc.cluster.local:8080
         -  id: home-front
            predicates:
            - Host=home.leedohyun.com
            uri: http://home-front.customer.svc.cluster.local:3000
         -  id: product-api
            predicates:
            - Host=product.leedohyun.com
            - Path=/api/products/**,/api/categories/**,/api/cart/**
            uri: http://product-api.customer.svc.cluster.local:8080
         -  id: order-api
            predicates:
            - Host=product.leedohyun.com
            - Path=/api/orders/**
            uri: http://order-api.customer.svc.cluster.local:8080
         -  id: product-front
            predicates:
            - Host=product.leedohyun.com
            uri: http://product-front.customer.svc.cluster.local:3000
         -  id: monitoring
            predicates:
            - Host=monitoring.leedohyun.com
            uri: http://monitoring-grafana.monitoring.svc.cluster.local:80
         -  id: router-admin
            predicates:
            - Host=router.leedohyun.com
            uri: https://leedohyun.asuscomm.com:8443
            filters:
            - SetRequestHeader=Host, leedohyun.asuscomm.com
            - SetRequestHeader=Origin, https://leedohyun.asuscomm.com:8443
            - SetRequestHeader=Referer, https://leedohyun.asuscomm.com:8443/Main_Login.asp
         httpclient:
            ssl:
               trustedX509Certificates:
               - classpath:router-admin-ca.pem
logging:
   level:
      root: INFO
      '[com.dh.gateway]': DEBUG
   pattern:
      console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
   charset:
      console: UTF-8
