spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
        - id : front
          predicates:
          - Host=front.leedohyun.com
          uri: http://home.front:3000
        - id : customer
          predicates:
          - Host=customer.leedohyun.com
          uri: http://customer.front:3000
        - id : wordpress
          predicates:
          - Host=wordpress.leedohyun.com
          uri: http://wordpress-01:80
        - id : tool
          predicates:
          - Host=tool.leedohyun.com
          uri: http://tool:8080