spring:
   application:
      name: gateway
   cloud:
      gateway:
         routes:
         -  id: tool
            predicates:
            - Host=tool.leedohyun.com
            uri: http://tool-service:80
            filters:
            - SetRequestHeader=Host, {request.headers.Host}
            - SetRequestHeader=Origin, {request.headers.Origin}
            - SetRequestHeader=Referer, {request.headers.Referer}
            - SetRequestHeader=Authorization, {request.headers.Authorization}
            - SetRequestHeader=Cookie, {request.headers.Cookie}
            - SetRequestHeader=X-Forwarded-For, {request.headers.X-Forwarded-For}
            - SetRequestHeader=X-Real-IP, {request.headers.X-Real-IP}
         -  id: wordpress
            predicates:
            - Host=leedohyun.com
            - Host=www.leedohyun.com
            - Host=blog.leedohyun.com
            - Host=wordpress.leedohyun.com
            uri: http://wordpress-service:80
            filters:
            - SetRequestHeader=Host, {request.headers.Host}
            - SetRequestHeader=Origin, {request.headers.Origin}
            - SetRequestHeader=Referer, {request.headers.Referer}
            - SetRequestHeader=Authorization, {request.headers.Authorization}
            - SetRequestHeader=Cookie, {request.headers.Cookie}
            - SetRequestHeader=X-Forwarded-For, {request.headers.X-Forwarded-For}
            - SetRequestHeader=X-Real-IP, {request.headers.X-Real-IP}
         -  id: minio-api
            predicates:
            - Host=static.leedohyun.com
            uri: http://minio-service:9000
            filters:
            - SetRequestHeader=Host, {request.headers.Host}
            - SetRequestHeader=Origin, {request.headers.Origin}
            - SetRequestHeader=Referer, {request.headers.Referer}
            - SetRequestHeader=Authorization, {request.headers.Authorization}
            - SetRequestHeader=Cookie, {request.headers.Cookie}
            - SetRequestHeader=X-Forwarded-For, {request.headers.X-Forwarded-For}
            - SetRequestHeader=X-Real-IP, {request.headers.X-Real-IP}
         -  id: minio-console
            predicates:
            - Host=minio.leedohyun.com
            uri: http://minio-console-service:9001
            filters:
            - SetRequestHeader=Host, {request.headers.Host}
            - SetRequestHeader=Origin, {request.headers.Origin}
            - SetRequestHeader=Referer, {request.headers.Referer}
            - SetRequestHeader=Authorization, {request.headers.Authorization}
            - SetRequestHeader=Cookie, {request.headers.Cookie}
            - SetRequestHeader=X-Forwarded-For, {request.headers.X-Forwarded-For}
            - SetRequestHeader=X-Real-IP, {request.headers.X-Real-IP}
         -  id: redmine
            predicates:
            - Host=alm.leedohyun.com
            - Host=redmine.leedohyun.com
            uri: http://redmine-service:3000
            filters:
            - SetRequestHeader=Host, {request.headers.Host}
            - SetRequestHeader=Origin, {request.headers.Origin}
            - SetRequestHeader=Referer, {request.headers.Referer}
            - SetRequestHeader=Authorization, {request.headers.Authorization}
            - SetRequestHeader=Cookie, {request.headers.Cookie}
            - SetRequestHeader=X-Forwarded-For, {request.headers.X-Forwarded-For}
            - SetRequestHeader=X-Real-IP, {request.headers.X-Real-IP}
         -  id: keycloak
            predicates:
            - Host=keycloak.leedohyun.com
            uri: http://keycloak-service:80
            filters:
            - SetRequestHeader=Host, {request.headers.Host}
            - SetRequestHeader=Origin, {request.headers.Origin}
            - SetRequestHeader=Referer, {request.headers.Referer}
            - SetRequestHeader=Authorization, {request.headers.Authorization}
            - SetRequestHeader=Cookie, {request.headers.Cookie}
            - SetRequestHeader=X-Forwarded-For, {request.headers.X-Forwarded-For}
            - SetRequestHeader=X-Real-IP, {request.headers.X-Real-IP}
         -  id: architecture
            predicates:
            - Host=architecture.leedohyun.com
            uri: http://architecture-service:80
            filters:
            - SetRequestHeader=Host, {request.headers.Host}
            - SetRequestHeader=Origin, {request.headers.Origin}
            - SetRequestHeader=Referer, {request.headers.Referer}
            - SetRequestHeader=Authorization, {request.headers.Authorization}
            - SetRequestHeader=Cookie, {request.headers.Cookie}
            - SetRequestHeader=X-Forwarded-For, {request.headers.X-Forwarded-For}
            - SetRequestHeader=X-Real-IP, {request.headers.X-Real-IP}
logging:
   level:
      root: INFO
      '[com.dh.gateway]': DEBUG
   pattern:
      console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
   charset:
      console: UTF-8