spring:
   application:
      name: gateway
   cloud:
      gateway:
         routes:
         -  id: front
            predicates:
            - Host=front.leedohyun.com
            uri: http://home.front:3000
         -  id: customer
            predicates:
            - Host=customer.leedohyun.com
            uri: http://customer.front:3000
         -  id: wordpress
            predicates:
            - Host=wordpress.leedohyun.com
            uri: http://wordpress-01:80
            filters:
            - SetRequestHeader=Host, {request.headers.Host}
            - SetRequestHeader=Origin, {request.headers.Origin}
            - SetRequestHeader=Referer, {request.headers.Referer}
            - SetRequestHeader=Authorization, {request.headers.Authorization}
            - SetRequestHeader=Cookie, {request.headers.Cookie}
            - SetRequestHeader=X-Forwarded-For, {request.headers.X-Forwarded-For}
            - SetRequestHeader=X-Real-IP, {request.headers.X-Real-IP}
         -  id: tool
            predicates:
            - Host=tool.leedohyun.com
            uri: http://tool:8080
            filters:
            - SetRequestHeader=Host, {request.headers.Host}
            - SetRequestHeader=Origin, {request.headers.Origin}
            - SetRequestHeader=Referer, {request.headers.Referer}
            - SetRequestHeader=Authorization, {request.headers.Authorization}
            - SetRequestHeader=Cookie, {request.headers.Cookie}
            - SetRequestHeader=X-Forwarded-For, {request.headers.X-Forwarded-For}
            - SetRequestHeader=X-Real-IP, {request.headers.X-Real-IP}
         -  id: auth
            predicates:
            - Host=auth.leedohyun.com
            uri: http://auth.api:8080
            filters:
            - SetRequestHeader=Host, {request.headers.Host}
            - SetRequestHeader=Origin, {request.headers.Origin}
            - SetRequestHeader=Referer, {request.headers.Referer}
            - SetRequestHeader=Authorization, {request.headers.Authorization}
            - SetRequestHeader=Cookie, {request.headers.Cookie}
            - SetRequestHeader=X-Forwarded-For, {request.headers.X-Forwarded-For}
            - SetRequestHeader=X-Real-IP, {request.headers.X-Real-IP}
         -  id: portainer
            predicates:
            - Host=portainer.leedohyun.com
            uri: http://portainer:9000
            filters:
            - SetRequestHeader=Host, {request.headers.Host}
            - SetRequestHeader=Origin, {request.headers.Origin}
            - SetRequestHeader=Referer, {request.headers.Referer}
            - SetRequestHeader=Authorization, {request.headers.Authorization}
            - SetRequestHeader=Cookie, {request.headers.Cookie}
            - SetRequestHeader=X-Forwarded-For, {request.headers.X-Forwarded-For}
            - SetRequestHeader=X-Real-IP, {request.headers.X-Real-IP}
         -  id: blog
            predicates:
            - Host=blog.leedohyun.com
            uri: http://wordpress-01:80
            filters:
            - SetRequestHeader=Host, {request.headers.Host}
            - SetRequestHeader=Origin, {request.headers.Origin}
            - SetRequestHeader=Referer, {request.headers.Referer}
            - SetRequestHeader=Authorization, {request.headers.Authorization}
            - SetRequestHeader=Cookie, {request.headers.Cookie}
            - SetRequestHeader=X-Forwarded-For, {request.headers.X-Forwarded-For}
            - SetRequestHeader=X-Real-IP, {request.headers.X-Real-IP}
         -  id: image
            predicates:
            - Host=image.leedohyun.com
            uri: http://minio-01:9000
            filters:
            - SetRequestHeader=Host, {request.headers.Host}
            - SetRequestHeader=Origin, {request.headers.Origin}
            - SetRequestHeader=Referer, {request.headers.Referer}
            - SetRequestHeader=Authorization, {request.headers.Authorization}
            - SetRequestHeader=Cookie, {request.headers.Cookie}
            - SetRequestHeader=X-Forwarded-For, {request.headers.X-Forwarded-For}
            - SetRequestHeader=X-Real-IP, {request.headers.X-Real-IP}
         -  id: image-minio
            predicates:
            - Host=image-minio.leedohyun.com
            - Host=static-minio.leedohyun.com
            - Path=/**
            uri: http://minio-01:9001
            filters:
            - SetRequestHeader=Host, {request.headers.Host}
            - SetRequestHeader=Origin, {request.headers.Origin}
            - SetRequestHeader=Referer, {request.headers.Referer}
            - SetRequestHeader=Authorization, {request.headers.Authorization}
            - SetRequestHeader=Cookie, {request.headers.Cookie}
            - SetRequestHeader=X-Forwarded-For, {request.headers.X-Forwarded-For}
            - SetRequestHeader=X-Real-IP, {request.headers.X-Real-IP}
         -  id: keycloak
            predicates:
            - Host=keycloak.leedohyun.com
            uri: http://keycloak:8080
            filters:
            - SetRequestHeader=Host, {request.headers.Host}
            - SetRequestHeader=Origin, {request.headers.Origin}
            - SetRequestHeader=Referer, {request.headers.Referer}
            - SetRequestHeader=Authorization, {request.headers.Authorization}
            - SetRequestHeader=Cookie, {request.headers.Cookie}
            - SetRequestHeader=X-Forwarded-For, {request.headers.X-Forwarded-For}
            - SetRequestHeader=X-Real-IP, {request.headers.X-Real-IP}
         -  id: main
            predicates:
            - Host=leedohyun.com
            - Host=www.leedohyun.com
            uri: http://wordpress-01:80
            filters:
            - SetRequestHeader=Host, {request.headers.Host}
            - SetRequestHeader=Origin, {request.headers.Origin}
            - SetRequestHeader=Referer, {request.headers.Referer}
            - SetRequestHeader=Authorization, {request.headers.Authorization}
            - SetRequestHeader=Cookie, {request.headers.Cookie}
            - SetRequestHeader=X-Forwarded-For, {request.headers.X-Forwarded-For}
            - SetRequestHeader=X-Real-IP, {request.headers.X-Real-IP}
         -  id: product
            predicates:
            - Host=product.leedohyun.com
            uri: http://front.product:3000
            filters:
            - SetRequestHeader=Host, {request.headers.Host}
            - SetRequestHeader=Origin, {request.headers.Origin}
            - SetRequestHeader=Referer, {request.headers.Referer}
            - SetRequestHeader=Authorization, {request.headers.Authorization}
            - SetRequestHeader=Cookie, {request.headers.Cookie}
            - SetRequestHeader=X-Forwarded-For, {request.headers.X-Forwarded-For}
            - SetRequestHeader=X-Real-IP, {request.headers.X-Real-IP}
         -  id: redmine
            predicates:
            - Host=redmine.leedohyun.com
            - Host=alm.leedohyun.com
            uri: http://redmine-01:3000
            filters:
            - SetRequestHeader=Host, {request.headers.Host}
            - SetRequestHeader=Origin, {request.headers.Origin}
            - SetRequestHeader=Referer, {request.headers.Referer}
            - SetRequestHeader=Authorization, {request.headers.Authorization}
            - SetRequestHeader=Cookie, {request.headers.Cookie}
            - SetRequestHeader=X-Forwarded-For, {request.headers.X-Forwarded-For}
            - SetRequestHeader=X-Real-IP, {request.headers.X-Real-IP}
         -  id: registry
            predicates:
            - Host=registry.leedohyun.com
            uri: http://registry-01:5000
            filters:
            - SetRequestHeader=Host, {request.headers.Host}
            - SetRequestHeader=Origin, {request.headers.Origin}
            - SetRequestHeader=Referer, {request.headers.Referer}
            - SetRequestHeader=Authorization, {request.headers.Authorization}
            - SetRequestHeader=Cookie, {request.headers.Cookie}
            - SetRequestHeader=X-Forwarded-For, {request.headers.X-Forwarded-For}
            - SetRequestHeader=X-Real-IP, {request.headers.X-Real-IP}
         -  id: resume
            predicates:
            - Host=resume.leedohyun.com
            uri: http://wordpress-02:80
            filters:
            - SetRequestHeader=Host, {request.headers.Host}
            - SetRequestHeader=Origin, {request.headers.Origin}
            - SetRequestHeader=Referer, {request.headers.Referer}
            - SetRequestHeader=Authorization, {request.headers.Authorization}
            - SetRequestHeader=Cookie, {request.headers.Cookie}
            - SetRequestHeader=X-Forwarded-For, {request.headers.X-Forwarded-For}
            - SetRequestHeader=X-Real-IP, {request.headers.X-Real-IP}
         -  id: router
            predicates:
            - Host=router.leedohyun.com
            uri: https://leedohyun.asuscomm.com:8443
            filters:
            - SetRequestHeader=Host, {request.headers.Host}
            - SetRequestHeader=Origin, {request.headers.Origin}
            - SetRequestHeader=Referer, {request.headers.Referer}
            - SetRequestHeader=Authorization, {request.headers.Authorization}
            - SetRequestHeader=Cookie, {request.headers.Cookie}
            - SetRequestHeader=X-Forwarded-For, {request.headers.X-Forwarded-For}
            - SetRequestHeader=X-Real-IP, {request.headers.X-Real-IP}
         -  id: static
            predicates:
            - Host=static.leedohyun.com
            uri: http://minio-01:9000
            filters:
            - SetRequestHeader=Host, {request.headers.Host}
            - SetRequestHeader=Origin, {request.headers.Origin}
            - SetRequestHeader=Referer, {request.headers.Referer}
            - SetRequestHeader=Authorization, {request.headers.Authorization}
            - SetRequestHeader=Cookie, {request.headers.Cookie}
            - SetRequestHeader=X-Forwarded-For, {request.headers.X-Forwarded-For}
            - SetRequestHeader=X-Real-IP, {request.headers.X-Real-IP}

logging:
   level:
      root: INFO
      '[com.dh.gateway]': DEBUG
   pattern:
      console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
   charset:
      console: UTF-8