spring:
   application:
      name: gateway
   cloud:
      gateway:
         routes:
         -  id: front
            predicates:
            - Host=front.leedohyun.com
            uri: http://home.front:3000
         -  id: customer
            predicates:
            - Host=customer.leedohyun.com
            uri: http://customer.front:3000
         -  id: tool
            predicates:
            - Host=tool.leedohyun.com
            uri: http://tool:8080
            filters:
            - SetRequestHeader=Host, {request.headers.Host}
            - SetRequestHeader=Origin, {request.headers.Origin}
            - SetRequestHeader=Referer, {request.headers.Referer}
            - SetRequestHeader=Authorization, {request.headers.Authorization}
            - SetRequestHeader=Cookie, {request.headers.Cookie}
            - SetRequestHeader=X-Forwarded-For, {request.headers.X-Forwarded-For}
            - SetRequestHeader=X-Real-IP, {request.headers.X-Real-IP}
         -  id: auth
            predicates:
            - Host=auth.leedohyun.com
            uri: http://auth.api:8080
         -  id: image
            predicates:
            - Host=image.leedohyun.com
            - Host=static.leedohyun.com
            uri: http://minio-01:9000
            filters:
            - SetRequestHeader=Host, {request.headers.Host}
            - SetRequestHeader=Origin, {request.headers.Origin}
            - SetRequestHeader=Referer, {request.headers.Referer}
            - SetRequestHeader=Authorization, {request.headers.Authorization}
            - SetRequestHeader=Cookie, {request.headers.Cookie}
            - SetRequestHeader=X-Forwarded-For, {request.headers.X-Forwarded-For}
            - SetRequestHeader=X-Real-IP, {request.headers.X-Real-IP}
         -  id: image-minio
            predicates:
            - Host=image-minio.leedohyun.com
            - Host=static-minio.leedohyun.com
            uri: http://minio-01:9001
            filters:
            - SetRequestHeader=Host, {request.headers.Host}
            - SetRequestHeader=Origin, {request.headers.Origin}
            - SetRequestHeader=Referer, {request.headers.Referer}
            - SetRequestHeader=Authorization, {request.headers.Authorization}
            - SetRequestHeader=Cookie, {request.headers.Cookie}
            - SetRequestHeader=X-Forwarded-For, {request.headers.X-Forwarded-For}
            - SetRequestHeader=X-Real-IP, {request.headers.X-Real-IP}
         -  id: keycloak
            predicates:
            - Host=keycloak.leedohyun.com
            uri: http://keycloak:8080
            filters:
            - SetRequestHeader=Host, {request.headers.Host}
            - SetRequestHeader=Origin, {request.headers.Origin}
            - SetRequestHeader=Referer, {request.headers.Referer}
            - SetRequestHeader=Authorization, {request.headers.Authorization}
            - SetRequestHeader=Cookie, {request.headers.Cookie}
            - SetRequestHeader=X-Forwarded-For, {request.headers.X-Forwarded-For}
            - SetRequestHeader=X-Real-IP, {request.headers.X-Real-IP}
         -  id: product
            predicates:
            - Host=product.leedohyun.com
            uri: http://front.product:3000
            filters:
            - SetRequestHeader=Host, {request.headers.Host}
            - SetRequestHeader=Origin, {request.headers.Origin}
            - SetRequestHeader=Referer, {request.headers.Referer}
            - SetRequestHeader=Authorization, {request.headers.Authorization}
            - SetRequestHeader=Cookie, {request.headers.Cookie}
            - SetRequestHeader=X-Forwarded-For, {request.headers.X-Forwarded-For}
            - SetRequestHeader=X-Real-IP, {request.headers.X-Real-IP}
logging:
   level:
      root: INFO
      '[com.dh.gateway]': DEBUG
   pattern:
      console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
   charset:
      console: UTF-8