spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
        - id: front
          predicates:
            - Host=front.leedohyun.com
          uri: http://home.front:3000
        - id: customer
          predicates:
            - Host=customer.leedohyun.com
          uri: http://customer.front:3000
        - id: wordpress
          predicates:
            - Host=wordpress.leedohyun.com
          uri: http://wordpress-01:80
        - id: tool
          predicates:
            - Host=tool.leedohyun.com
          uri: http://tool:8080
        - id: auth
          predicates:
            - Host=auth.leedohyun.com
          uri: http://auth.api:8080
        - id: portainer
          predicates:
            - Host=portainer.leedohyun.com
          uri: http://portainer:9000
        - id: blog
          predicates:
            - Host=blog.leedohyun.com
          uri: http://wordpress-01:80
        - id: git
          predicates:
            - Host=git.leedohyun.com
            - Host=gitlab.leedohyun.com
            - Host=gitlab1.leedohyun.com
            - Host=gitlab2.leedohyun.com
          uri: http://gitlab-01:80
        - id: image
          predicates:
            - Host=image.leedohyun.com
          uri: http://minio-01:9000
        - id: image-minio
          predicates:
            - Host=image-minio.leedohyun.com
            - Host=static-minio.leedohyun.com
          uri: http://minio-01:9001
        - id: imap
          predicates:
            - Host=imap.leedohyun.com
            - Host=mail.leedohyun.com
          uri: http://mailserver:443
        - id: keycloak
          predicates:
            - Host=keycloak.leedohyun.com
          uri: http://keycloak:8080
        - id: main
          predicates:
            - Host=leedohyun.com
            - Host=www.leedohyun.com
          uri: http://wordpress-01:80
        - id: npm
          predicates:
            - Host=npm.leedohyun.com
          uri: http://nginx-proxy-manager:81
        - id: product
          predicates:
            - Host=product.leedohyun.com
          uri: http://front.product:3000
        - id: redmine
          predicates:
            - Host=redmine.leedohyun.com
            - Host=alm.leedohyun.com
          uri: http://redmine-01:3000
        - id: registry
          predicates:
            - Host=registry.leedohyun.com
          uri: http://registry-01:5000
        - id: resume
          predicates:
            - Host=resume.leedohyun.com
          uri: http://wordpress-02:80
        - id: router
          predicates:
            - Host=router.leedohyun.com
          uri: http://leedohyun.asuscomm.com:8443
        - id: static
          predicates:
            - Host=static.leedohyun.com
          uri: http://minio-01:9000
        - id: tt
          predicates:
            - Host=tt.leedohyun.com
          uri: http://home.front:3000